// Generated by adsterra-code-handoff. Public browser configuration only.
// Domain: scarygrocerythenightshift.com
// Do not edit manually; rerun the handoff when placements change.
export const adsterraStaticConfig = {
  adsterraBannerId: "ec2a350a62f3115ff1efed66a377556c",
  adsterraBanner300x250Key: "ec2a350a62f3115ff1efed66a377556c",
  adsterraBanner300x250ScriptUrl: "https://www.highperformanceformat.com/ec2a350a62f3115ff1efed66a377556c/invoke.js",
  adsterraBanner320x50Key: "fda5073c274a5aca5f61fa31cf996343",
  adsterraBanner320x50ScriptUrl: "https://www.highperformanceformat.com/fda5073c274a5aca5f61fa31cf996343/invoke.js",
  adsterraBanner728x90Key: "64711225ce43be4a11c70727bb1bcfbb",
  adsterraBanner728x90ScriptUrl: "https://www.highperformanceformat.com/64711225ce43be4a11c70727bb1bcfbb/invoke.js",
  adsterraNative1Id: "container-10ab21e05f3c27f8f55864289993afb9",
  adsterraNative1ScriptUrl: "https://pl30203326.effectivecpmnetwork.com/10ab21e05f3c27f8f55864289993afb9/invoke.js",
  adsterraLeaderboardId: "64711225ce43be4a11c70727bb1bcfbb",
  adsterraEnablePopunder: false,
  adsterraEnableSocialBar: false,
  adsterraEnableStickyRail: false,
  adsterraPopunderDelayMs: 30000,
  adsterraPopunderMinPageViews: 2,
} as const;

export const adsterraStaticEnv = {
  NEXT_PUBLIC_ADSTERRA_BANNER_300X250_KEY: "ec2a350a62f3115ff1efed66a377556c",
  NEXT_PUBLIC_ADSTERRA_BANNER_300X250_SCRIPT_URL: "https://www.highperformanceformat.com/ec2a350a62f3115ff1efed66a377556c/invoke.js",
  NEXT_PUBLIC_ADSTERRA_BANNER_320X50_KEY: "fda5073c274a5aca5f61fa31cf996343",
  NEXT_PUBLIC_ADSTERRA_BANNER_320X50_SCRIPT_URL: "https://www.highperformanceformat.com/fda5073c274a5aca5f61fa31cf996343/invoke.js",
  NEXT_PUBLIC_ADSTERRA_BANNER_728X90_KEY: "64711225ce43be4a11c70727bb1bcfbb",
  NEXT_PUBLIC_ADSTERRA_BANNER_728X90_SCRIPT_URL: "https://www.highperformanceformat.com/64711225ce43be4a11c70727bb1bcfbb/invoke.js",
  NEXT_PUBLIC_ADSTERRA_ENABLE_POPUNDER: "false",
  NEXT_PUBLIC_ADSTERRA_ENABLE_SOCIAL_BAR: "false",
  NEXT_PUBLIC_ADSTERRA_ENABLE_STICKY_RAIL: "false",
  NEXT_PUBLIC_ADSTERRA_NATIVE_1_ID: "container-10ab21e05f3c27f8f55864289993afb9",
  NEXT_PUBLIC_ADSTERRA_NATIVE_1_SCRIPT_URL: "https://pl30203326.effectivecpmnetwork.com/10ab21e05f3c27f8f55864289993afb9/invoke.js",
  NEXT_PUBLIC_ADSTERRA_POPUNDER_DELAY_MS: "30000",
  NEXT_PUBLIC_ADSTERRA_POPUNDER_MIN_PAGEVIEWS: "2",
} as const;
